### ISSUE TITLE
Bug - Uncaught Error: Cannot find module 'season'.

### ISSUE THREAD

**Issue by ghost** [romgrk/termrk#53]
Hello

This error occurs right after upgrading to 0.1.25 and also reinstalling the package:

```
Error: Cannot find module 'season'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (~/.atom/packages/Termrk/lib/termrk.coffee:11:10)
    at Object.<anonymous> (~/.atom/packages/Termrk/lib/termrk.coffee:523:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

Thanks in advance

**Comment by Gys** [comment]
Having the same problem :-(

**Atom Version**: 1.0.7
**System**: Mac OS X 10.10.4

**Comment by romgrk** [comment]
Patch published, update package and it should be fixed. :)
Forgot to add 'season' in dependencies.

**Comment by romgrk** [comment]
Fixed by efdaf40c8942d31fbc42c4e7f09c03d55e363ca5.
